import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { cookieToInitialState } from "wagmi";
import "./globals.css";
import { config } from "@/config";
import { Web3ModalProvider } from "@/context";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en">
      <body className="font-encode bg-[#0c0b0b] text-[#ffd700]">
        <Web3ModalProvider initialState={initialState}>
          <Navbar />
          <div>{children}</div>
          <Footer />
          <Toaster richColors />
        </Web3ModalProvider>
      </body>
    </html>
  );
}
